# Numpy

NumPy (singkatan dari Numerical Python) adalah "pondasi" dari hampir semua alat Machine Learning dan Data Science di Python.

di dalam Numpy ini kita tidak bisa mengisi data sembarangan melainkan harus setipe atau sejenis dan list dengan Numpy berbeda

-- dimana list lambat dalam menhitung atau menganalisis dan tipe data ini bisa mencapur atau menampung semua jenis data di dalam nya.



-- sedangkan Numpy tidak bisa dicampur melainkan data nya harus sama

# Array 0D (Skalar)

In [20]:
array_0d = np.array(1)
print(array_0d.ndim)

0


# Array 1D (Vector)

In [1]:
# contoh penerapan numpy di python

# Analisis Penjualan Toko

import numpy as np

penjualan = np.array([120,150,90,200,130,80,160])

# Operasi Statistik dasar
nilai_terendah = np.min(penjualan)
nilai_tertinggi = np.max(penjualan)
rata_rata = np.mean(penjualan)

print (f" nilai terendah penjualan yaitu {nilai_terendah}")
print (f" nilai tertinggi penjualan yaitu {nilai_tertinggi}")
print (F" Rata - rata penjualan nya yaitu {rata_rata}")

# Boolean Indexing
penjualan_bagus = penjualan[penjualan>rata_rata]
print (f" penjualan yang bagus berada di atas rata rata yaitu {penjualan_bagus}")

# Slicing
weekend_sales = np.sum(penjualan[-2:])
print (f" Penjualan akhir pekan berada di total {weekend_sales}")


 nilai terendah penjualan yaitu 80
 nilai tertinggi penjualan yaitu 200
 Rata - rata penjualan nya yaitu 132.85714285714286
 penjualan yang bagus berada di atas rata rata yaitu [150 200 160]
 Penjualan akhir pekan berada di total 240


# Array 2D (matrix)

jadi terdapat array 2d dimana ini sebuah representasi dari baris data yang mempunya sebuah baris dan kolom

contoh seperti ini :
sebuat daftar nilai mahasiswa dimana baris mewakili mahasiswa itu sendiri dan kolom mewakili mata kuliah

nah di Numpy kita membuat sebuah array 2d ini dengan cara menumpuk beberapa list dalam satu kurung siku besar []

dalam library Numpy kita punya atribut dimana tugasnya mengetahui ukuran data yang kita punya dengan memberikan informasi tentang
baris dan kolom yaitu atribut ".shape"

In [2]:
# contoh pembuatan array 2d

import numpy as np

nilai_kelas = np.array([
    [80,90],
    [70,85],
    [95,100]
])

# tampilan array 2d
print(nilai_kelas)

# mengetahui ukuran data menggunakan atribut (.shape)
print(f"ukuran data nilai_kelas yaitu {nilai_kelas.shape}")

# membuat operasi statistik dasar nilai tertinggi dari 2d array
tertinggi = np.max(nilai_kelas)
print(f"nilai tertinggi dari seluruh mahasiswa yaitu {tertinggi}")

# menggunakan slicing method untuk mahasiswa ke-3 dan mencari rata-rata
mahasiswa_3 = np.mean(nilai_kelas[2])
print(f"rata-rata nilai dari mahasiswa ke-3 yaitu {mahasiswa_3}")


[[ 80  90]
 [ 70  85]
 [ 95 100]]
ukuran data nilai_kelas yaitu (3, 2)
nilai tertinggi dari seluruh mahasiswa yaitu 100
rata-rata nilai dari mahasiswa ke-3 yaitu 97.5


penggunaan fitur axis di Numpy untuk mencari rata rata keseluruhan baik mahasiswa ataupun matakuliah

In [3]:
# rata-rata nilai dari 3 mahasiswa
mean_mahasiswa = np.mean(nilai_kelas, axis=1)
print(f"rata-rata nilai dari ketiga mahasiswa yaitu {mean_mahasiswa}")

# rata-rata nilai keseluruhan mata kuliah
mean_matakuliah = np.mean(nilai_kelas, axis=0)
print(f"rata-rata nilai dari kedua matakuliah yaitu {mean_matakuliah}")

rata-rata nilai dari ketiga mahasiswa yaitu [85.  77.5 97.5]
rata-rata nilai dari kedua matakuliah yaitu [81.66666667 91.66666667]


apa itu axis di library numpy?

axis itu merupakan sebuah perhitungan atau pengoperasian otomatis dari setiap data tanpa melakukan nya satu per satu (vektorisasi)
jadi axis itu berkaita dengan atribut shape dimana (0 = fokus ke baris,1 = fokus ke kolom)

# array 3D (Tensor)
array ini mempunya 3 dimensi dan harus konsisten di tiap  dimensi nya
(Kedalaman/lapisan, Baris, Kolom)

In [18]:
array_3D = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]])

print(array_3D)

print("mengetahui dimensi array dengan fungsi .ndim")
print(array_3D.ndim)

print("mengetahui ukuran dimensi array dengan fungsi .shape")
print(array_3D.shape)



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
mengetahui dimensi array dengan fungsi .ndim
3
mengetahui ukuran dimensi array dengan fungsi .shape
(2, 3, 3)


## Reshaping

Reshaping merupakan sebuah proses mengubah bentuk dimensi data tanpa mengubah isinya, biasanya merupakan data mentah yang panjang dan ingin kita ubah menjadi table agar bisa diolah dengan axis

In [4]:
# contoh reshaping

# Reshaping Data Suhu
data_suhu = np.array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36])
data_suhu2D = data_suhu.reshape(4,3)

print(data_suhu2D)
print(f"Ukuran data_suhu2D yaitu {data_suhu2D.shape}")


[[25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]]
Ukuran data_suhu2D yaitu (4, 3)


## .ndim

".ndim" merupakan sebuah atribut yang memberi tahu jumlah dimensi dari data array tsb.

In [5]:
data_suhu2D.ndim

2

# Integrasi Data di Numpy

In [6]:
import numpy as np

# Data Mentah (Sensor A: Suhu, Sensor B: Kelembaban)
sensor_a = np.array([20.5, 21.0, 19.8, -99.0, 22.5], dtype='float32')
sensor_b = np.array([45.2, 46.1, -99.0, 48.0, 47.5], dtype='float32')

# TUGAS 1: Gabungkan menjadi matriks 2D berukuran (5, 2)
# Gunakan np.column_stack atau np.vstack dengan transpose
# Tulis kodemu di bawah ini:

Matriks_Sensor_ab = np.column_stack((sensor_a, sensor_b))
print(Matriks_Sensor_ab.shape)

hasil = np.transpose(np.vstack((sensor_a, sensor_b)))
print(hasil.shape)

(5, 2)
(5, 2)


# Pembersihan Data (Boolean Indexing)

In [7]:

# DATA MENTAH (Skenario: Sensor Cuaca di Puncak Gunung)
# Kolom 0: Suhu (Celcius)
# Kolom 1: Kelembaban (%)
data_gunung = np.array([
    [15.5, 80.0],
    [-999.0, 85.0],
    [14.8, -999.0],
    [16.2, 88.0],
    [-999.0, 82.0],
    [15.0, 84.0]
], dtype='float32')

print("Data Mentah:")
print(data_gunung)

# Cleaning Data suhu menggunakan Boolean dan Mean
data_suhu_bersih = np.mean(data_gunung[data_gunung[:, 0] != -999.0 ,0])
print(data_suhu_bersih)
# Cleaning Data kelembapan menggunakan Boolean dan Median
data_kelembapan_bersih = np.median(data_gunung[data_gunung[:, 1] != -999.0 ,1])
print(data_kelembapan_bersih)

# mengganti value error (-999.0) dari data_gunung
data_gunung[data_gunung[:, 0] == -999.0 ,0] = data_suhu_bersih
data_gunung[data_gunung[:, 1] == -999.0 ,1] = data_kelembapan_bersih
print("Hasil Data yang sudah Bersih: ")
print(data_gunung)


Data Mentah:
[[  15.5   80. ]
 [-999.    85. ]
 [  14.8 -999. ]
 [  16.2   88. ]
 [-999.    82. ]
 [  15.    84. ]]
15.375
84.0
Hasil Data yang sudah Bersih: 
[[15.5   80.   ]
 [15.375 85.   ]
 [14.8   84.   ]
 [16.2   88.   ]
 [15.375 82.   ]
 [15.    84.   ]]


# The .copy() Method

Method ini menduplikat dataset yang kita punya dan tidak memengaruhi dataset asli nya jika kita melakukan experimen di dataset duplikat, namun jika kita menggunakan syntax seperti ini "dataset_baru = dataset" (ini akan memengaruhi dataset asli nya).

In [8]:
import numpy as np

# Data asli kita (Umur, Skor)
data_asli = np.array([
    [20, 85],
    [21, 90],
    [19, 78],
    [22, 92]
], dtype='int32')

print("Data Asli (Awal):\n", data_asli)

# Kita buat 'data_eksperimen' hanya dengan tanda =
data_eksperimen = data_asli 

# Ceritanya kita mau coba-coba: 'Bagaimana kalau skor mahasiswa pertama (0,1) kita ubah jadi 100?'
data_eksperimen[0, 1] = 100

print("Data Eksperimen (Sudah diubah):\n", data_eksperimen)
print("\n--- CEK DATA ASLI ---")
print(data_asli)

Data Asli (Awal):
 [[20 85]
 [21 90]
 [19 78]
 [22 92]]
Data Eksperimen (Sudah diubah):
 [[ 20 100]
 [ 21  90]
 [ 19  78]
 [ 22  92]]

--- CEK DATA ASLI ---
[[ 20 100]
 [ 21  90]
 [ 19  78]
 [ 22  92]]


In [9]:
# Balikin dulu data asli ke skor awal (85)
data_asli[0, 1] = 85

# KALI INI PAKAI .copy()
data_cadangan = data_asli.copy()

# Ubah skor mahasiswa pertama di data_cadangan jadi 0 (ceritanya kena sanksi)
data_cadangan[0, 1] = 0

print("Data Cadangan (Skor jadi 0):\n", data_cadangan)
print("\n--- CEK DATA ASLI (Harusnya Aman) ---")
print(data_asli)

Data Cadangan (Skor jadi 0):
 [[20  0]
 [21 90]
 [19 78]
 [22 92]]

--- CEK DATA ASLI (Harusnya Aman) ---
[[20 85]
 [21 90]
 [19 78]
 [22 92]]


# Aritmatika di Numpy



aritmatika adalah cabang tertua dan paling dasar dari matematika yang mempelajari operasi angka. Jika matematika adalah sebuah bangunan, maka aritmatika adalah fondasinya.


In [5]:
# Skalar Aritmatika 
import numpy as np

array = np.array([1,2,3])

# Operasi Aritmatika skalar
print(array + 1)
print(array - 1)
print(array * 2)
print(array / 2)
print(array ** 2)
print(array % 2)



[2 3 4]
[0 1 2]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]
[1 0 1]


In [11]:
# vektor aritmatika

angka = np.array([1.01, 2.6, 4.70])

print(np.sqrt(angka))            # akar jumlah dari array yang dibuat
print(np.round(angka))           # pembulatan angka normal

print(np.floor (angka))          # pembulatan ke bawah
print(np.ceil(angka))            # pembulatan ke atas

# contoh menghitung luas lingkaran dengan jari - jari (r) nya yaitu angka
Luas_lingkaran = np.pi * angka ** 2
print(Luas_lingkaran)

[1.00498756 1.61245155 2.16794834]
[1. 3. 5.]
[1. 2. 4.]
[2. 3. 5.]
[ 3.20473867 21.23716634 69.39778172]


In [15]:
# Operasi antar elemen Aritmatika (element wise)

array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

# Penjumlahan antar elemen
print(array1 + array2)

# Pengurangan antar elemen
print(array1 - array2)

# Perkalian antar elemen
print(array1 * array2)

# Pembagian antar elemen
print(array1 / array2)

# pangkat antar elemen
print(array1 ** array2)





[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [19]:
# operasi perbandingan (comparison operator)

nilai_mahasiswa = np.array([80, 90, 70, 60, 50])

# perbandingan lebih dari 70 
print(nilai_mahasiswa > 70)      # output nya akan keluar True atau False

nilai_mahasiswa[nilai_mahasiswa < 70] = 0

# nilai sama dan dibawah 70 tidak lulus dan diubah menjadi 0
print(nilai_mahasiswa)


[ True  True False False False]
[80 90 70  0  0]


# Broadcasting di Numpy

broadcasting adalah "kemampuan ajaib" yang memungkinkan library ini melakukan operasi aritmatika pada array dengan bentuk (shape) yang berbeda.

Aturan Utama Broadcasting
Agar dua array bisa di-broadcast, NumPy membandingkan dimensinya mulai dari paling kanan (trailing dimensions). Dua dimensi kompatibel jika:



1. Ukurannya sama, atau
2. Salah satunya berukuran 1.

In [4]:

import numpy as np
# Membuat matrix dan row vector
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_vec = np.array([10, 20, 30])

# ukuran matrix dan row vector
print(matrix.shape)
print(row_vec.shape)

print("\n")
# operasi aritmatika
print(matrix + row_vec)
# Hasilnya tiap baris akan ditambah 10, 20, dan 30

(3, 3)
(3,)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


# Fungsi Agregat di Numpy

Fungsi Agregat memiliki tugas berupa merangkum data yang tadi nya memiliki nilai banyak menjadi satu nilai atau istilah nya memberi summary 

In [4]:
import numpy as np
list_umur = [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

print(np.max(list_umur))  # ini merupakan salah satu fungsi agregasi 

print(np.min(list_umur))

print(np.mean(list_umur))

print(np.median(list_umur))

print(np.std(list_umur))


30
20
25.0
25.0
3.1622776601683795


# Filtering di Numpy

Filtering di NumPy adalah proses mengambil elemen tertentu dari sebuah array berdasarkan kondisi atau kriteria yang kamu tentukan. Bayangkan kamu punya sekumpulan data, dan kamu hanya ingin mengambil angka yang lebih besar dari 10 atau angka yang genap saja—itulah filtering.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# 1. Membuat kondisi (mask)
kondisi = arr > 3  # Hasilnya: [False, False, False, True, True]

# 2. Filtering
hasil = arr[kondisi]

print(hasil) # Output: [4, 5]

[4 5]


Contoh Kondisi Ganda

# Menggunakan operator & (AND)
hasil_kompleks = arr[(arr > 2) & (arr % 2 == 0)]
print(hasil_kompleks) # Output: [4]

In [2]:
# Menggunakan operator & (AND)
hasil_kompleks = arr[(arr > 2) & (arr % 2 == 0)]
print(hasil_kompleks) # Output: [4]

[4]


# Bilangan Acak di Numpy

Di pustaka NumPy (Python), bilangan acak adalah deretan angka yang dihasilkan oleh algoritma komputer sehingga polanya terlihat tidak terduga, mirip dengan hasil lemparan dadu atau koin.

In [17]:
rng = np.random.default_rng(seed=1)

print(rng.integers(low=1,high=101,size=(3,3)))


[[48 52 76]
 [96  4 15]
 [83 95 25]]


In [16]:
np.random.seed(seed=1)

print(np.random.uniform(low=-2,high=1,size=(3,2)))

[[-0.74893399  0.16097348]
 [-1.99965688 -1.09300228]
 [-1.55973233 -1.72298422]]


In [23]:
mbg = np.random.default_rng()

buah = np.array(["🍊","🍌","🍓","🥕","🍒"])
buah = mbg.choice(buah, size=(3,3))
print(buah)

[['🍓' '🍓' '🍓']
 ['🍊' '🥕' '🥕']
 ['🍓' '🍓' '🍌']]
