In [1]:
# challenge 1

import numpy as np

rng = np.random.default_rng(seed=42)
market_data = rng.integers(low=100, high=200, size=(10, 3))
print(market_data)

[[108 177 165]
 [143 143 185]
 [108 169 120]
 [109 152 197]
 [173 176 171]
 [178 151 112]
 [183 145 150]
 [137 118 192]
 [178 164 140]
 [182 154 144]]


In [2]:
# challenge 2 (analisis statistik)

# Hitung rata-rata (mean) untuk setiap kolom open, high, low, close.
print(np.mean(market_data, axis = 0))

# cari harga tertinggi secara global
print(np.max(market_data))

# hitung standart deviasi (std) untuk melihat volatilitas pasar secara kesuluruhan
print(np.std(market_data))


[149.9 154.9 157.6]
197
26.172165027414568


In [5]:
# challenge 3

# penyesuain harga (broadcasting)
# kurangi seluruh isi market data dengan angka 2.5
# pembulatan hasil 2 angka dibelakang koma
print(np.round(market_data - 2.5, 2))

[[105.5 174.5 162.5]
 [140.5 140.5 182.5]
 [105.5 166.5 117.5]
 [106.5 149.5 194.5]
 [170.5 173.5 168.5]
 [175.5 148.5 109.5]
 [180.5 142.5 147.5]
 [134.5 115.5 189.5]
 [175.5 161.5 137.5]
 [179.5 151.5 141.5]]


In [6]:
# challenge 4
# filtering & multiple conditions
hari_bagus = market_data[(market_data[:,0]>180) & (market_data[:,2]<150)]
print(hari_bagus)

[[182 154 144]]


In [7]:
# challenge 5
# buat array bernama signal 
signal = np.array(np.where(market_data[:,2] > 170, "SELL", "HOLD"))
print(signal)



['HOLD' 'SELL' 'HOLD' 'SELL' 'SELL' 'HOLD' 'HOLD' 'SELL' 'HOLD' 'HOLD']


In [13]:
# challenge 6
# Sorting Close dari market_data terbesar ke terkecil
sorting_descending = np.sort(market_data[:, 2])[::-1]
print(sorting_descending)



[197 192 185 171 165 150 144 140 120 112]
