# praktik pembuatan Numpy (1d,2d,3d)

In [1]:
import numpy as np

modal = 1000
# Target: Buat array berisi faktor perkaliannya (1.05 untuk 5%, dst)
pertumbuhan = np.array([1.05, 1.10, 1.15, 1.20]) 

# Lakukan perkalian skalar dengan vektor (Vectorization)
hasil_akhir = pertumbuhan * modal

print("Proyeksi Modal:", hasil_akhir)

Proyeksi Modal: [1050. 1100. 1150. 1200.]


In [2]:
price_close_eurusd = np.array([1.1138,1.11422,1.11482,1.1143,1.1142])

# tipe data
print(price_close_eurusd.dtype)

# ukuran byte memori untuk satu harga
print(price_close_eurusd.itemsize)

# ukuran byte dari total array 
print(price_close_eurusd.nbytes)


float64
8
40


In [3]:
data_pasar = np.array([
    [[1.11521,1.11562,1.11378,1.1138],[14908.26,15004.35,14863.81,14944.35]],
    [[1.1138,1.11447,1.11354,1.11422],[15001.01,15047.25,14931.88,14972.76]]])

# bentuk_dimensi 
print(data_pasar.shape)
    
# ukuran/jumlah dimensi
print(data_pasar.ndim)

(2, 2, 4)
3


In [4]:
# indexing
target = data_pasar[1, 1, 2]
print(target)

14931.88


In [5]:
# Ambil SEMUA harga (OHLC) untuk Aset pertama di Hari pertama
print(data_pasar[0, 0, :])

[1.11521 1.11562 1.11378 1.1138 ]


# Praktik Slicing di Numpy

In [6]:
# 1D (Vector) Slicing

# membuat array 1d dengan data Harga Penutupan Nasdaq
price_close = np.array([14944.35,14972.76,14970.18,14969.65,14857.71,14843.77,14524.07,14510.30,14592.21,14765.94])

# Slicing harga dari indeks ke-3 sampai ke-7
print("Harga indeks - 3 sampe indeks - 7")
print(price_close[3:8])

# Pembalikan Data menggunakan step
print("Pembalikan Data")
print(price_close[::-1])


Harga indeks - 3 sampe indeks - 7
[14969.65 14857.71 14843.77 14524.07 14510.3 ]
Pembalikan Data
[14765.94 14592.21 14510.3  14524.07 14843.77 14857.71 14969.65 14970.18
 14972.76 14944.35]


In [7]:
# 2D (Matriks) Slicing

# membuat array 2D (5x4) dengan data harga nasdaq seminggu
price_week_nasdaq = np.array([
    [14129.96,14149.62,13982.42,14031.81],
    [13994.54,14060.85,13945.65,14020.95],
    [13988.81,14001.95,13802.42,13872.47],
    [13675.11,13774.63,13642.47,13748.83],
    [13754.71,13843.37,13733.18,13761.53]])

# Ekstrak hanya kolom High (indeks 1) dan Low (indeks 2) untuk semua baris.
print("High (indeks 1) dan Low (indeks 2) untuk semua baris.")
print(price_week_nasdaq[: ,1:3])

# Ambil hanya 3 baris terakhir untuk semua kolom.
print("3 baris terakhir untuk semua kolom.")
print(price_week_nasdaq[2:])

# negatif indexing Ambil data Close (kolom terakhir) pada Baris terakhir
print("data Close (kolom terakhir) pada Baris terakhir")
print(price_week_nasdaq[-1: ,-1])

High (indeks 1) dan Low (indeks 2) untuk semua baris.
[[14149.62 13982.42]
 [14060.85 13945.65]
 [14001.95 13802.42]
 [13774.63 13642.47]
 [13843.37 13733.18]]
3 baris terakhir untuk semua kolom.
[[13988.81 14001.95 13802.42 13872.47]
 [13675.11 13774.63 13642.47 13748.83]
 [13754.71 13843.37 13733.18 13761.53]]
data Close (kolom terakhir) pada Baris terakhir
[13761.53]


In [8]:
open_high_datapasar = data_pasar[: , : ,0:2]
print(open_high_datapasar.shape)

(2, 2, 2)


# Praktikum Aritmatika di Numpy

In [9]:
import numpy as np


# chalengge 1

# data image gambar di matrix
image = np.array([
    [11,45,24],
    [47,20,12],
    [12,23,45]
])

# tambah kecerahan gambar dengan nilai 100(skalar)
print("image + 100")
print(image + 100)


# Kalikan dengan 10 supaya banyak angka yang lewat dari 255
print("Test Overexposure:")
print(np.clip(image * 10, 0, 255))     # membuat threshold dengan ufunc np.clip()

image + 100
[[111 145 124]
 [147 120 112]
 [112 123 145]]
Test Overexposure:
[[110 255 240]
 [255 200 120]
 [120 230 255]]


In [10]:
# challenge 2
data_kecepatan = np.array([9.81, 19.62, 29.43, 39.24])

# pembulatan angka ke terdekat
print(np.round(data_kecepatan, 0))

# Power 
print(np.power(data_kecepatan, 2)) 

[10. 20. 29. 39.]
[  96.2361  384.9444  866.1249 1539.7776]


In [11]:
# challenge 3
mahasiswa_trilogi = np.array([
    [[80, 90, 87, 98], [75, 85, 82, 93], [90, 100, 97, 80]],
    [[85, 80, 97, 88], [65, 75, 72, 83], [70, 90, 87, 70]]
])

# Global Max 
print("global max")
print(np.max(mahasiswa_trilogi))

# Mean Haerul
print("mean haerul")
print(np.mean(mahasiswa_trilogi[:,0,:])) # rata rata nilai haerul di semua matkul

# axis challenge
print("mean matkul")
print(np.mean(mahasiswa_trilogi, axis=1)) 


global max
100
mean haerul
88.125
mean matkul
[[81.66666667 91.66666667 88.66666667 90.33333333]
 [73.33333333 81.66666667 85.33333333 80.33333333]]


# Praktik Broadcast Numpy

In [12]:
# Scalar Broadcasting (challenge 1)
import numpy as np

data_gaji = np.array([3,4,5,6,7])

bonus_gaji = data_gaji * 1.2

gaji_bersih = bonus_gaji + 0.5

print(gaji_bersih)

[4.1 5.3 6.5 7.7 8.9]


In [13]:
# challenge 2

# membuat array dimensi 2D (3x4) 
data_nilai = np.array([
    [80, 70, 90,85],
    [75, 85, 80,82],
    [90, 80, 85,76],
])

# menampilkan array dan ukuran array
print(data_nilai)
print(data_nilai.shape)

# poin tambahan
tambahan = [5, 2, 10, 0]    # Array 1D 

# Broadcast array tambahan ke setiap baris
nilai_baru = data_nilai + tambahan
print(nilai_baru)



[[80 70 90 85]
 [75 85 80 82]
 [90 80 85 76]]
(3, 4)
[[ 85  72 100  85]
 [ 80  87  90  82]
 [ 95  82  95  76]]


In [14]:
# chalengge 3

import numpy as np

A = np.ones([4, 3])
B = np.arange(3)       # Shape (3,)
C = np.arange(4)       # Shape (4,)
D = np.arange(4).reshape(4, 1) # Shape (4, 1)

# tampilan dari masing masing array
print(A)            
print(B)
print(C)
print(D)

print("hasil dari A + B")
# cek shape untuk penyocokan array
print(A.shape)
print(B.shape)
print(A + B)        # berhasil tidak error

'''
# cek shape untuk penyocokan array
print(A.shape)
print(C.shape)
print("hasil dari A + C")
print(A + C)        # berhasil tidak error 
'''
# cek shape untuk penyocokan array
print(A.shape)
print(D.shape)
print("hasil dari A + D")
print(A + D)        # berhasil tidak error



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]
hasil dari A + B
(4, 3)
(3,)
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
(4, 3)
(4, 1)
hasil dari A + D
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [15]:
import numpy as np

# challenge 1 

# data array foto_3D
foto_3D = np.array([
    [[100,100,100]],
    [[100,100,100]]
])

print(foto_3D)

# data filter 
filter = np.array([50,-20,0])

# test shape per array 
print(foto_3D.shape)
print(filter.shape)

# menjumlahkan filter dengan foto_3D
print(foto_3D + filter)




[[[100 100 100]]

 [[100 100 100]]]
(2, 1, 3)
(3,)
[[[150  80 100]]

 [[150  80 100]]]


In [16]:
# challenge 2

# data array zero_2d
zero_2d = np.zeros([5,5])

# Misi A tambahkan angka
variasi_angka1 = np.array([1,2,3,4,5])
print(zero_2d)

print("\n")
# dijumlahkan 
print(zero_2d + variasi_angka1)

print("\n")
# Misi B tambahkan angka
variasi_angka2 = np.array([10,20,30,40,50]).reshape(5,1)
print(variasi_angka2)

print("\n")
# dijumlahkan
print(zero_2d + variasi_angka2)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


[[10]
 [20]
 [30]
 [40]
 [50]]


[[10. 10. 10. 10. 10.]
 [20. 20. 20. 20. 20.]
 [30. 30. 30. 30. 30.]
 [40. 40. 40. 40. 40.]
 [50. 50. 50. 50. 50.]]


# Praktik Fungsi Agregat Numpy

In [28]:
# challenge 1
import numpy as np

# data kecepatan bola
kecepatan_bola = np.array(np.random.randint(0, 11, size=10))
print(kecepatan_bola)

# Nilai minimum
print("Nilai minimum")
print(kecepatan_bola.min())

# nilai maksimum
print("Nilai maksimum")
print(kecepatan_bola.max())

# total kecepatan
print("Total kecepatan")
print(kecepatan_bola.sum())



[ 3  6  4 10  3  7  6 10  1 10]
Nilai minimum
1
Nilai maksimum
10
Total kecepatan
60


In [18]:
# chalenge 2

score_mahasiswa = np.array([
    [80,78,87,92],
    [90,85,88,91],
    [75,80,82,89]
])

print(score_mahasiswa.shape)
print(score_mahasiswa)

# rata-rata nilai matakuliah
print(score_mahasiswa.mean(axis=0))

# rata-rata nilai mahasiswa
print(score_mahasiswa.mean(axis=1))


(3, 4)
[[80 78 87 92]
 [90 85 88 91]
 [75 80 82 89]]
[81.66666667 81.         85.66666667 90.66666667]
[84.25 88.5  81.5 ]


In [19]:
# challenge 3

# membuat 2 array
data_stabil = [80, 81, 79, 80]
data_acak = [100, 50, 150, 20]

print(np.std(data_stabil))
print(np.std(data_acak))

# kesimpulan
"""
harga data stabil lebih rendah dibandingkan harga data acak karena data acak memiliki perbandingan angka yang sangat jauh satu sama lain
"""

0.7071067811865476
49.49747468305833


'\nharga data stabil lebih rendah dibandingkan harga data acak karena data acak memiliki perbandingan angka yang sangat jauh satu sama lain\n'

In [20]:
import numpy as np
# challenge 

# Baris: Haerul, Budi, Siti
# Kolom: Kalkulus, Pemrograman, Jaringan, AI
nilai_mahasiswa = np.array([
    [85, 90, 78, 92], # Nilai Haerul
    [70, 85, 80, 75], # Nilai Budi
    [95, 80, 85, 88]  # Nilai Siti
])

print(nilai_mahasiswa.shape)

# Tugas A (rata-rata nilai tiap matkul)
print(nilai_mahasiswa.mean(axis=0))

# Tugas B (rata-rata nilai tiap mahasiswa)
print(nilai_mahasiswa.mean(axis=1))

(3, 4)
[83.33333333 85.         81.         85.        ]
[86.25 77.5  87.  ]


# Praktik Filtering di Numpy

In [21]:
import numpy as np

# chalengge 1 

# data nilai uas
nilai_uas = np.array([80, 65, 90, 50, 76, 88, 40])

# filter nilai yang lulus diatas 75 dari data nilai_uas
lulus = nilai_uas[nilai_uas > 75]

# menampilkan nilai yang lulus diatas 75
print("Nilai yang lulus: ")
print(lulus)

# filter nilai yang remidi dibawah 75 dari data nilai_uas
remidi = nilai_uas[nilai_uas < 75]

# menampilkan nilai yang remidi dibawah 75
print("Nilai yang remidi: ")

print(remidi)




Nilai yang lulus: 
[80 90 76 88]
Nilai yang remidi: 
[65 50 40]


In [22]:
# chalengge 2 

# membuat sebuah variabel berisi data hasil trading 
data_trading = np.array([-100, 200, 50, -50, 400, 0, -20])

# filtering hasil trading profit > 0
profit_plus = data_trading[data_trading > 0]
# menampilkan hasil filtering 
print("hasil trading profit (+): ")
print(profit_plus)

# filtering hasil trading profit lebih dari 100
huge_profit = data_trading[data_trading > 100]
# menampilkan hasil filtering
print("hasil trading profit lebih dari 100: ")
print(huge_profit)

# filtering hasil trading loss atau Break Even
loss_BE = data_trading[(data_trading < 0) | (data_trading == 0)]
# menampilkan hasil Filtering
print("hasil trading Loss/Be: ")
print(loss_BE)

# filtering hasil trading profit dibawah 100
profit_under100 = data_trading[(data_trading > 0) & (data_trading < 100)]
# menampilkan hasil Filtering
print("hasil trading Profit < 100: ")
print(profit_under100)


hasil trading profit (+): 
[200  50 400]
hasil trading profit lebih dari 100: 
[200 400]
hasil trading Loss/Be: 
[-100  -50    0  -20]
hasil trading Profit < 100: 
[50]


In [23]:
# challenge 3

# penggunaan np.where ()

# data hasil trading 
hasil_trading = np.array([10, -5, 20, 0, -15, 30])

# filter data dan melabeli data
print(np.where(hasil_trading > 0, "Buy", "Wait"))


['Buy' 'Wait' 'Buy' 'Wait' 'Wait' 'Buy']


In [24]:
trade_sejarah = np.array([
    [10, -5, 20],  
    [30, 0, -10]   
])

print(np.sort(trade_sejarah, axis=1))

print(np.sort(trade_sejarah, axis=0)[::-1])



[[ -5  10  20]
 [-10   0  30]]
[[ 30   0  20]
 [ 10  -5 -10]]


# Bil. Acak Praktik

In [25]:
# chalengge 1
np.random.seed(seed=3) # menyimpan hasil angka acak agar tetap sama jika dipake lagi 
array = np.sort(np.random.randint(low=1,high=101,size=3)) # sorting dari terkecil ke terbesar
print(array)

[ 4 25 57]


In [ ]:

# challenge 2

# strategi trading
strategi_trading = np.array(["ICT 2022", "Judas Swing", "SMT Divergence", "Fair Value Gaps"])

strategi_pilihan = np.random.choice(strategi_trading, size=3, replace=False)
print(strategi_pilihan)

['SMT Divergence' 'Judas Swing' 'Fair Value Gaps']


In [27]:
# challenge 3

np.random.seed(seed=2)
matriks = np.random.rand(4,3)
print(matriks)

matriks_pengurangan = matriks - 0.5
min = matriks_pengurangan.min()
max = matriks_pengurangan.max()

print(f"matriks saya berada di rentang {min} sampai {max}")


[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467]
 [0.26682728 0.62113383 0.52914209]]
matriks saya berada di rentang -0.47407376817210867 sampai 0.1211338327692949
